version: '3.9'
services:
  nginx-reversed-proxy:
    image: nginx:alpine
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
    hostname: host.docker.internal
    volumes:
      - ./conf.d/:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: host
